# Generated by Django 5.2.5 on 2025-09-03 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='carousel/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='active',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='address',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='contact',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='course',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='requests/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='name',
            field=models.CharField(default='Anonymous', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.service'),
        ),
    ]
